name: CI/CD Pipeline for DevOps

on:
  push:
    paths:
      - 'app/**'
  pull_request:
    paths:
      - 'app/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, Tag, and Push Docker Image
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: my-webapp-repository
          IMAGE_NAME: tasktest
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build the Docker image
          docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .

          # Push both tags to the repository
          docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

      - name: Create Dockerrun.aws.json
        run: |
          REGISTRY="${{ env.REGISTRY }}"
          REPOSITORY="${{ env.REPOSITORY }}"
          IMAGE_TAG="${{ env.IMAGE_TAG }}"
          IMAGE_URI="$REGISTRY/$REPOSITORY:$IMAGE_TAG"

          cat > Dockerrun.aws.json << 'EOF'
          {
            "AWSEBDockerrunVersion": "2",
            "containerDefinitions": [
              {
                "name": "web-container",
                "image": "$IMAGE_URI",
                "portMappings": [
                  {
                    "containerPort": 8080,
                    "hostPort": 80
                  }
                ],
                "essential": true,
                "memory": 128
              }
            ]
          }
          EOF

      - name: Zip Dockerrun.aws.json
        run: |
          zip deployment_package.zip Dockerrun.aws.json

      - name: Deploy to AWS Elastic Beanstalk
        if: github.event_name == 'push'
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: devops-project-test-free-tier-eb-env  # Your EB application name
          environment_name: devops-project-test-free-tier-eb-env    # Your EB environment name
          version_label: ${{ github.sha }}
          region: us-east-1
          deployment_package: deployment_package.zip